blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://www.angulartoolbox.com/#/CONTRIBUTING
    about: Please check the documentation for questions before submitting an issue.
